import React, { useState } from "react";
import axios from "axios";
import { Spinner, Alert } from "reactstrap";
import { Link } from "react-router-dom";
import AdminNav from "./AdminNav";
import AdminFooter from "./AdminFooter";



const AdminReg = () => {
  const [adminname, setadminname] = useState("");
  const [adminmail, setadminmail] = useState("");

  const [issending, setissending] = useState(false);
  const [showalert, setshowalert] = useState(false);
  const [alert, setalert] = useState("");


  function Register(e) {
    if(adminname, adminmail){
      setissending(true)
      const data = new FormData();
      data.append("adminname", adminname);
      data.append("adminmail", adminmail);
      data.append("action", "01");
      data.append("admintoken", "ABULESOWO")
      data.append("apptoken", "ZC20AD91QR");

      axios
      .post(`https://api.abulesowo.ng`, data, {
        // headers: {
        //   "content-type": "multipart/form-data",
        // },
      })
      .then((res) => {
        console.log(res.data);
     
        if (res.data.response == "01") {

          setshowalert(true);
          setadminname("")
          setadminmail("")
          setalert(res.data.message);

          setissending(false);
        } else {
          setshowalert(true);
          setalert(res.data.message);
          setissending(false);
        }
      })
      .catch((error) => {
        console.log(error.name);
        setshowalert(true);
        setalert(error.name);
        setissending(false);
      });
      
    }else{
       setshowalert(true)
       setalert('Empty fields')
       setissending(false)
     }
    e.preventDefault();
  }






    return ( 
      <>
      <AdminNav/>
        <section class="adminlogin">
            <div class="container">
            <h3 class="text-center">Admin Register</h3>
            {showalert ? (
                <>
                  <Alert color="success">{alert}</Alert>
                </>
              ) : (
                <></>
              )}
            <form>
                <div class="row justify-content-center mt-5">
                <div class="col-md-8">
                    <label> Full Name </label>

                    <div class="input-group mb-4">
                      <input
                        type="text"
                        class="form-control"
                        onChange={(e) => setadminname(e.target.value)}
                        value={adminname}
                        required
                      />
                    </div>
                  </div>

                  <div class="col-md-8">
                    <label> Email </label>

                    <div class="input-group mb-4">
                      <input
                        type="email"
                        class="form-control"
                        onChange={(e) => setadminmail(e.target.value)}
                        value={adminmail}
                        required
                      />
                    </div>
                  </div>

                  <div class="col-md-8">
                    <label> Password </label>

                    <div class="input-group mb-4">
                      <input
                        type="password"
                        class="form-control"
                        placeholder="It will be autogenerated, check your email"
                        disabled 
                      />
                    </div>
                  </div>
                <div class="col-md-12  mx-auto text-center">

                {issending ? (
                      <>
                        <button
                          type="button"
                          class="btn shadow"
                          action="submit"
                        >
                          {" "}
                          <strong>
                            {" "}
                            Logging In <Spinner color="light" />{" "}
                          </strong>
                        </button>
                      </>
                    ) : (
                      <>
                        <button
                          type="button"
                          class="btn shadow waves-effect"
                          action="submit"
                          onClick={(e) => Register(e)}
                        >
                          {" "}
                          <strong> register </strong>{" "}
                        </button>
                      </>
                    )}

                    <h6> Already have an acct? <Link to="/adminlogin">Login</Link> </h6>
            </div>
            </div>
         
  
              </form>
                
            </div>
        </section>
        <AdminFooter/>
        </>
     );
}
 
export default AdminReg;