import img from '../assets/img.png'

export const listing = [
    {
        name: "A new 4 bedroom Bungalow in Bodija",
        price: "40,000,000",
        img: `${img}`,
        token: "S1AT",
        location: "Bodija, Oyo State",
        type: "sales",
        bedroom: "4",
        bathroom: "5",
        toilet: "3",
        sqrmeter: "300",
        parking: "3",
        yearbuilt: "2000",
        desc: "A new 4 bedroom Bungalow in Bodija",
        hotdeals: "0",

    },
    {
        name: "Warehouse For Sale In Between Tollgate To Iwo Road, Ibadan, Oyo",
        price: "90,000,000",
        img: `${img}`,
        token: "AJ292B",
        location: "In Between Tollgate To Iwo Road, Ibadan, Oyo",
        type: "sales",
        // bedroom: "4",
        // bathroom: "5",
        // toilet: "3",
        sqrmeter: "6,000",
        parking: "10",
        yearbuilt: "2000",
        desc: "Warehouse at ibadan tollgate along lagos ibadan express way 6000sqm warehouse around tollgate iwo road area ibadan a land mass of *6000sqm* with a factory warehousing seating on *5200sqm include with staff quarters,d compound were tiles,like 15 offices * in between tollgate to iwo road ibadan. doc: reg.",
        hotdeals: "1",

    },
    {
        name: "15 Bedroom House For Sale at  Sobanjo Close, Jericho, Ibadan, Oyo",
        price: "350,000,000",
        img: `${img}`,
        token: "IS22W",
        location: " Sobanjo Close, Jericho, Ibadan, Oyo",
        type: "sales",
        bedroom: "15",
        bathroom: "10",
        toilet: "8",
        sqrmeter: "7500",
        parking: "3",
        yearbuilt: "1990",
        desc: "This property is located at sobanjo close off jericho/idi ishin road, ibadan. the features include: 1. the main building which has 2 living rooms and ten (10) bedrooms; 2 dining rooms; 2 kitchens and 2 stores. 2. the bungalow has the following: 1 living room; 4 bedrooms; 1 dining room; 1 kitchen and a store. title document is a registered conveyance.",
        hotdeals: "0",

    },
    {
        name: "16 Bedroom House For Sale at Challenge, Ibadan, Oyo",
        price: "100,000,000",
        img: `${img}`,
        token: "KNE49",
        location: "Beside State Terminal, Near Challenge Roundabout, Challenge, Ibadan, Oyo",
        type: "sales",
        bedroom: "16",
        bathroom: "4",
        toilet: "7",
        sqrmeter: "4,009",
        parking: "6",
        yearbuilt: "2000",
        desc: "This is a strategic mixed- use 16 bedrooms tenement storey building with the following features it has 16 bedrooms, 4 on each wing each wing has 1 toilet bathroom and kitchen the bedrooms are spacious it is fenced and gated at the back so the car park can take up to 6 cars this property is the 4th plot to the challenge tarred road, making it suitable for both residential and commercial purposes like hotel, school and so on it is not far from newly constructed challenge terminal there are verifiable documents for serious buyers for more details and inspection",
        hotdeals: "1",

    },




    {
        name: "2 bedroom flat in Akobo for Rent",
        price: "1,305,000",
        img: `${img}`,
        token: "BE3J",
        location: "Akobo, Oyo State",
        type: "rent",
        bedroom: "2",
        bathroom: "5",
        toilet: "3",
        sqrmeter: "300",
        parking: "3",
        yearbuilt: "2000",
        desc: "A new 2 bedroom flat in Akobo for Rent",
        hotdeals: "0",

    },
    {
        name: "6 bedroom flat in Orogun for Rent",
        price: "705,000",
        img: `${img}`,
        token: "KNU23",
        location: "Orogun, Oyo State",
        type: "rent",
        bedroom: "6",
        bathroom: "5",
        toilet: "3",
        sqrmeter: "300",
        parking: "4",
        yearbuilt: "2000",
        desc: "6 bedroom flat in Orogun for Rent",
        hotdeals: "0",

    },
    {
        name: "2 Bedroom Flat / Apartment For Rent at  Aromakinde, Ojoo, Ibadan, Oyo",
        price: "2,500,000",
        img: `${img}`,
        token: "JSB89",
        location: " Aromakinde, Ojoo, Ibadan, Oyo",
        type: "rent",
        bedroom: "2",
        bathroom: "3",
        toilet: "3",
        sqrmeter: "1,200",
        parking: "2",
        yearbuilt: "2019",
        desc: "A lovely 2 bedroom flat at aromakinde, ojoo, ibadan. the apartment is fully tiled, full pop, all rooms ensuite with visitors toilet, wardrobes, kitchen cabinets and other modern facilities.",
        hotdeals: "1",

    },
    {
        name: "4 Bedroom Detached Bungalow For Rent at New Bodija, Ibadan, Oyo",
        price: "2,500,000",
        img: `${img}`,
        token: "JSBU20",
        location: "New Bodija, Ibadan, Oyo",
        type: "rent",
        bedroom: "4",
        bathroom: "4",
        toilet: "4",
        sqrmeter: "1,900",
        parking: "3",
        yearbuilt: "2017",
        desc: "A four bedroom bungalow, self compound with 2 rooms bq. all rooms ensuite, ac fitted, spacious compound, two sitting rooms, three stores for the kitchen, generator included in the lease. it's located around sma, new bódìjà. rent: ₦2.5m per annum",
        hotdeals: "1",

    },



    {
        name: "15 Arces of Land for sale in Agodi GRA",
        price: "15,500,000",
        img: `${img}`,
        token: "SH73",
        location: "Agodi GRA, Oyo State",
        type: "land",
        sqrmeter: "15 Arces of Land",
        desc: "15 Arces of Land for sale in Agodi GRA",
        hotdeals: "0",

    },
    {
        name: "Residential Land For Sale Ologuneru, Ibadan, Oyo",
        price: "2,000,000",
        img: `${img}`,
        token: "ICN3D",
        location: "London Park And Gardens, Ologuneru, Ibadan, Oyo",
        type: "land",
        sqrmeter: "540 sq meters",
        desc: "London park and gardens ologuneru, ibadan oyo state. this estate has all the infrastructures that will provide comfortability for people in the estate. the actual price is 2m you can enjoy massive discount with the current lemon friday promo note: the price exclude the documentation and developmental fees upon readiness to build 40% discount: 1,200,000 payment within 12 months 50% discount: 1,000,000 payment within 6 months",
        hotdeals: "1",

    },
    {
        name: "Land For Sale Ayegun Oleyo Akala Express Road, Ibadan, Oyo",
        price: "15,500,000",
        img: `${img}`,
        token: "SM98X",
        location: "Ayegun Oleyo Akala Express Road, Ibadan, Oyo",
        type: "land",
        sqrmeter: "540 sq meters",
        desc: "West park and gardens phase 1 ayegun oleyo actual price: 4m enjoy massive discount of 40% discount payment within 12 months discounted price: 2.4m 50% discount is 2,000,000 payment within 6 months reach me now!!!! note: the price exclude the documentation and developmental fees ",
        hotdeals: "1",

    },
    {
        name: "15 Arces of Land for sale at Asejire, Ibadan, Oyo",
        price: "20,500,000",
        img: `${img}`,
        token: "SH8BQ73",
        location: "City Park And Garden Phase 1, Asejire Opposite Coca Cola Company, Asejire, Ibadan, Oyo",
        type: "land",
        sqrmeter: "15 Arces of Land",
        desc: "This is making incredibles affordable. the estate is conducive and full is unique infrastructural facilities which ensure comfortability. city park and gardens is a fresh addition to our renowned theme parks and gardens estates. it is structurally planned to further enrich the exciting history of asejire town- breathing air of freshness, making excellent and affordable planned housing accessible to every discerning investor estate feature : perimeter fencing,good drainage system, security lights, good electricity system etc.. enjoy lemon friday promo 2022 actual price: 3m 50% discount: 1.5m note: the price exclude the documentation and developmental fees",
        hotdeals: "0",

    },


]